### ISSUE TITLE
"Exception while parsing NVD CVE feed" when no vulnerability found 

### ISSUE THREAD

**Issue by jerryline** [AppThreat/dep-scan#28]
It runs OK several days before, but recently it went to this exception when scanning the same project:

WARNING [2020-12-28 08:40:27,572] Exception while parsing NVD CVE feed
Traceback (most recent call last):
  File "/usr/local/bin/scan", line 33, in <module>
    sys.exit(load_entry_point('appthreat-depscan==1.9.2', 'console_scripts', 'scan')())
  File "/usr/local/lib/python3.8/site-packages/appthreat_depscan-1.9.2-py3.8.egg/depscan/cli.py", line 293, in main
    s.refresh()
  File "/usr/local/lib/python3.8/site-packages/appthreat_vulnerability_db-1.5.2-py3.8.egg/vdb/lib/nvd.py", line 95, in refresh
    return self.download_all()
  File "/usr/local/lib/python3.8/site-packages/appthreat_vulnerability_db-1.5.2-py3.8.egg/vdb/lib/nvd.py", line 51, in download_all
    self.store(data)
  File "/usr/local/lib/python3.8/site-packages/appthreat_vulnerability_db-1.5.2-py3.8.egg/vdb/lib/nvd.py", line 100, in store
    docs = dbLib.store(db, data)
  File "/usr/local/lib/python3.8/site-packages/appthreat_vulnerability_db-1.5.2-py3.8.egg/vdb/lib/db.py", line 61, in store
    docs = storage.store(datas, db_file=db["db_file"], index_file=db["index_file"])
  File "/usr/local/lib/python3.8/site-packages/appthreat_vulnerability_db-1.5.2-py3.8.egg/vdb/lib/storage.py", line 17, in store
    data_list = serialize_vuln_list(datas)
  File "/usr/local/lib/python3.8/site-packages/appthreat_vulnerability_db-1.5.2-py3.8.egg/vdb/lib/utils.py", line 146, in serialize_vuln_list
    for data in datas:
TypeError: 'NoneType' object is not iterable

But all is OK about 10 days before:

![image](https://user-images.githubusercontent.com/21166817/103343524-3e5a8880-4ac7-11eb-8562-16614bbe571e.png)

It seems that it cannot found any vulnerability recently, it should give a message like "No vulnerability  detected", but runs into this exception. But I am not sure of it.

**Comment by prabhu** [comment]
Yeah, failing for me as well. Investigating ...

**Comment by prabhu** [comment]
Thanks for reporting this issue.

Just one bad CPE value in the NVD database broke depscan!

```
cpe:2.3:a:oracle:communications_diameter_signaling_router_idih\::*:*:*:*:*:*:*:*
```

In the above value, not only there is a problematic backslash, the version part following the string `communications_diameter_signaling_router_idih` is empty instead of `*`. We know the quality of NVD is often lacking but this is unexpected.

I have added some workarounds to guard against this here:

https://github.com/AppThreat/vulnerability-db/commit/f73308f57e65ef13402577ef68786ba06963c185

scan image is rebuilt to include this fix now.

**Comment by jerryline** [comment]
@prabhu  very thanks for the quick fixing of the issue, you mentioned that the scan image is rebuilt, but I found that the latest image for "quay.io/appthreat/dep-scan:latest" is still 3 months ago.

**Comment by jerryline** [comment]
@prabhu  Very thanks for your quick fixing on this issue,  I'm using "appthreat/dep-scan:latest", it failed again. I'm not very familiar with this, it there anything need to be updated on "appthreat/dep-scan:latest"?

**Comment by prabhu** [comment]
@jerryline Are you able to use the parent project called slscan?

https://slscan.io/en/latest/

-t depscan would invoke depscan. I will see if I can update this particular image separately.

**Comment by prabhu** [comment]
There was a bug in the dockerfile so recent "appthreat/dep-scan" docker builds were failing. This is now resolved and the latest image has got built successfully. But would highly recommend moving to slscan since it has got a bit more rich feature set and scanning tools.
