### ISSUE TITLE
New version of dep-scan is missing a dependency "quart"

### ISSUE THREAD

**Issue by jchli** [AppThreat/dep-scan#96]
My [GitHub Actions builds](https://github.com/marketplace/actions/dep-scan) are failing with the following:

```
Run AppThreat/dep-scan-action@master
  with:
    src: /github/workspace
    report_file: /github/workspace/reports/depscan.json
  env:
    IsRunningOnCI: true
    Environment: Test
    DOTNET_ROOT: /home/runner/.dotnet
    VDB_HOME: /home/runner/work/carrot-app/carrot-app/db
    GITHUB_TOKEN: ***
/usr/bin/docker run --name ghcrioappthreatdepscanlatest_fe0993 --label 49859c --workdir /github/workspace --rm -e "IsRunningOnCI" -e "Environment" -e "DOTNET_ROOT" -e "VDB_HOME" -e "GITHUB_TOKEN" -e "INPUT_SRC" -e "INPUT_REPORT_FILE" -e "INPUT_BOM" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/carrot-app/carrot-app":"/github/workspace" ghcr.io/appthreat/dep-scan:latest  "depscan" "--src" "/github/workspace" "--report_file" "/github/workspace/reports/depscan.json" "--suggest"
Traceback (most recent call last):
  File "/usr/local/bin/depscan", line 33, in <module>
    sys.exit(load_entry_point('appthreat-depscan==4.0.0', 'console_scripts', 'depscan')())
  File "/usr/local/bin/depscan", line [2](https://github.com/carrotfertility/carrot-app/actions/runs/4305322894/jobs/7507590998#step:6:2)5, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python[3](https://github.com/carrotfertility/carrot-app/actions/runs/4305322894/jobs/7507590998#step:6:3).9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib6[4](https://github.com/carrotfertility/carrot-app/actions/runs/4305322894/jobs/7507590998#step:6:4)/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 8[5](https://github.com/carrotfertility/carrot-app/actions/runs/4305322894/jobs/7507590998#step:6:5)0, in exec_module
  File "<frozen importlib._bootstrap>", line 22[8](https://github.com/carrotfertility/carrot-app/actions/runs/4305322894/jobs/7507590998#step:6:8), in _call_with_frames_removed
  File "/usr/local/lib/python3.[9](https://github.com/carrotfertility/carrot-app/actions/runs/4305322894/jobs/7507590998#step:6:9)/site-packages/appthreat_depscan-4.0.0-py3.9.egg/depscan/cli.py", line 9, in <module>
    from quart import Quart, request
ModuleNotFoundError: No module named 'quart'
```

**Comment by prabhu** [comment]
@jchli, I am unsure what is going on here. I have tried some fixes to the github action and pushed it as v4. Could you try that version instead of the master?

**Comment by prabhu** [comment]
@jchli, could you confirm if this is still failing for you?

**Comment by jchli** [comment]
@prabhu Still getting the same error

**Comment by prabhu** [comment]
Can replicate the issue on GitHub actions. Suspecting some environment variable injected by GitHub is causing the issue.

```
/usr/bin/docker run --name ghcrioappthreatdepscanlatest_b19703 --label 49859c --workdir /github/workspace --rm -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "VDB_HOME" -e "GITHUB_TOKEN" -e "INPUT_SRC" -e "INPUT_REPORT_FILE" -e "INPUT_BOM" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/dep-scan/dep-scan":"/github/workspace" ghcr.io/appthreat/dep-scan:latest  "--src" "/github/workspace" "--report_file" "/github/workspace/reports/depscan.json" "--suggest"
```

**Comment by prabhu** [comment]
https://github.com/AppThreat/dep-scan/actions/runs/4310837010/jobs/7519664142

**Comment by prabhu** [comment]
@jchli could you retry by re-running the workflows?

**Comment by jchli** [comment]
Looks like we’re clear. What ended up being the root cause?

**Comment by prabhu** [comment]
@jchli GitHub action seems to be injecting itself while doing docker run. So kept changing the dockerfile till it worked.
